@startuml
title JavaScript模块化历史

actor 开发者

note over 开发者: 2002年
开发者 -> 开发者: 使用命名空间模式解决命名冲突

note over 开发者: 2003年
开发者 -> 开发者: 使用模块模式实现代码和数据隔离

note over 开发者: 2009年
开发者 -> 开发者: 使用CommonJS模块规范实现模块同步加载

note over 开发者: 2010年左右
开发者 -> 开发者: 使用AMD格式实现模块异步加载

note over 开发者: 2011年左右
开发者 -> 开发者: 使用UMD模式解决模块系统的代码适配问题

note over 开发者: 2015年
开发者 -> 开发者: 使用ES Module实现官方标准的模块化

@enduml
